"""empty message

Revision ID: 469b0e3436d8
Revises: 36b93d81ad60
Create Date: 2015-02-18 12:29:45.038097

"""

# revision identifiers, used by Alembic.
revision = '469b0e3436d8'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Pocasi', sa.String(), nullable=False),
    sa.Column('Den', sa.String(), nullable=False),
    sa.Column('Rok', sa.String(), nullable=False),
    sa.Column('Mesic', sa.String(), nullable=False),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Den', 'loguser', ['Den'], unique=False)
    op.create_index('ix_loguser_Mesic', 'loguser', ['Mesic'], unique=False)
    op.create_index('ix_loguser_Rok', 'loguser', ['Rok'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_Rok', table_name='loguser')
    op.drop_index('ix_loguser_Mesic', table_name='loguser')
    op.drop_index('ix_loguser_Den', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
